### ISSUE TITLE
RStudio crashes if file is opened when writing to it

### ISSUE THREAD

**Issue by sda030** [davidgohel/officer#360]
It is of course ill-adviced to try to print(rdocx) or print(rpptx) to a file that is accidentally open, but having RStudio and even Rgui crash is unexpected. I notice that there seem to be a check in the function of whether the file is open, but perhaps not working properly? I am using Windows 10.

``` r
library(officer)
x <- read_pptx()
print(x, "tmp.pptx") # While having the tmp.pptx file open.
```

![image](https://user-images.githubusercontent.com/13221371/114195102-75ef9100-9950-11eb-9b65-dc830f2dde6d.png)

**Comment by davidgohel** [comment]
Could you please add `sessionInfo()`?

**Comment by sda030** [comment]
``` r
sessionInfo()
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Norwegian Bokmål_Norway.1252 
#> [2] LC_CTYPE=Norwegian Bokmål_Norway.1252   
#> [3] LC_MONETARY=Norwegian Bokmål_Norway.1252
#> [4] LC_NUMERIC=C                            
#> [5] LC_TIME=Norwegian Bokmål_Norway.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.31        magrittr_2.0.1    rlang_0.4.10      fansi_0.4.2      
#>  [5] stringr_1.4.0     styler_1.4.1      highr_0.8         tools_4.0.4      
#>  [9] xfun_0.22         utf8_1.2.1        withr_2.4.1       htmltools_0.5.1.1
#> [13] ellipsis_0.3.1    yaml_2.2.1        digest_0.6.27     tibble_3.1.0     
#> [17] lifecycle_1.0.0   crayon_1.4.1      purrr_0.3.4       vctrs_0.3.7      
#> [21] fs_1.5.0          glue_1.4.2        evaluate_0.14     rmarkdown_2.7    
#> [25] reprex_2.0.0      stringi_1.5.3     compiler_4.0.4    pillar_1.5.1     
#> [29] backports_1.2.1   pkgconfig_2.0.3
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by davidgohel** [comment]
Thak you, but I need to know what version of officer you are using

**Comment by sda030** [comment]
Ah, sorry, still learning how reprex works..
officer_0.3.18

**Comment by davidgohel** [comment]
Thanks, it will take some time as I need to test that on a windows computer.

**Comment by davidgohel** [comment]
thanks, this is fixed now

**Comment by RedemptionArc** [comment]
Hi David,

I'm running version 0.3.18 and RStudio is still crashing under the conditions described above (Windows 10, Rstudio 1.4.1106 - writing to OneDrive).

Any advice on how to avoid it?

Regards,
Michael

**Comment by davidgohel** [comment]
@RedemptionArc It fixed, you are using a version that does not contain the fix. Please install the dev version
