### ISSUE TITLE
Still happening: Section break type changed by officer

### ISSUE THREAD

**Issue by arkglobo** [davidgohel/officer#481]
Hello,
this is actually the same issue as [Section break type changed by officer](https://github.com/davidgohel/officer/issues/230)

I have a document with two section breaks (both types are "Next page". The second one gets changed by officer to "continuous".

Is there a fix for that? Thanks and best regards,

**Comment by davidgohel** [comment]
Yes it is fixed as indicated

**Comment by arkglobo** [comment]
Thanks for your quick reply. Unfortunately, I still have this issue and I could not find any solution how to make it work.

**Comment by davidgohel** [comment]
What issue, I don't see any reproducible example nor sessionInfo(). You asked: 

> Is there a fix for that? [about an issue of 2019...]

My answer is "yes, it is fixed" (I have no idea what you are talking about)

**Comment by arkglobo** [comment]
Hi David, thank you and sorry, for the misunderstanding. I assumed it was not necessary because I linked the other issue.

So I included my starting document below: officer_test_template.docx which has two [section breaks](https://support.microsoft.com/en-us/office/use-section-breaks-to-change-the-layout-or-formatting-in-one-section-of-your-document-4cdfa638-3ea9-434a-8034-bf1e4274c450) , with a _next page_ command. When I print the new document after running my R-script it changes the second section break to _continuous_ (See document test-print.docx)

Let me know if you need more information. Kind regards,






[officer_test_template.docx](https://github.com/davidgohel/officer/files/11028567/officer_test_template.docx)
[test-print.docx](https://github.com/davidgohel/officer/files/11028568/test-print.docx)


My code is:

`
#Load packages
library(tidyverse)
library(officer)
library(png)

#set wd
setwd(dirname(rstudioapi::documentPath()))

#define template name
word_template <- "officer_test_template.docx"

#read template
bericht <- read_docx(word_template)

#get available dimensions of template to define new width of plot
word_size_p <- read_docx(path = paste0(dirname(rstudioapi::documentPath()),"/", word_template)) %>% docx_dim()

#Define new plot width
img_width <- word_size_p$page['width'] - word_size_p$margins['left'] - word_size_p$margins['right']


#Platzhalter definieren, müssen ggf. angepasst werden
PLACEHOLDER_TEST <-     "r-meme.png"

img_size <- dim(png::readPNG(PLACEHOLDER_TEST))/300
#choose image hight and set scale for word paste (33%)
img_height <- img_size[1]/3

#replace placeholder with image
doc_img <- cursor_reach(bericht, PLACEHOLDER_TEST)
doc_img <- body_add_img(doc_img, 
                        src = paste0(PLACEHOLDER_TEST),
                        width = img_width, height = img_height)
doc_img <- cursor_reach(bericht, PLACEHOLDER_TEST)
doc_img <- body_remove(doc_img)


#save wordfile
print(doc_img, "test-print.docx")

`

**Comment by davidgohel** [comment]
Here is a minimal reproducible example (at least r-meme.png was missing)

```
library(officer)
bericht <- read_docx("officer_test_template.docx")
print(bericht, "test-print.docx")
```

'officer' manages section since some time now. This comes with a price, users that want to play with sections should manage sections on their own. Here, as there is no defined type of default section nor any indication of what type of sections are the non default, 'officer' decided it was 'continuous' and added this into the default section settings. 

We don't want to remove that piece of logic as it would make a regression (for those who manage portrait and landscape sections).

The solution is to specify the section you want, I think it also could be defining the default section as it seems you want a page break between each sections.

```
library(officer)
bericht <- read_docx("officer_test_template.docx")
bericht <- body_end_block_section(bericht, block_section(prop_section(type = "nextPage")))
print(bericht, "test-print.docx")
```

**Comment by arkglobo** [comment]
Thank you, it works with setting the default!
